logsBucket: "gs://scam-scam-logging-bucket"
steps:
  - name: "gcr.io/cloud-builders/cd"
    args: ["scam-scam"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/cd"
    args: [".."]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "scam-scam-service"
      - "--source=scam-scam/dist"
      - "--region=us-central1"
      - "--platform=managed"
